import { Geist, Geist_Mono, Arimo, PT_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";


const arimo = Arimo({
  variable: "--font-aramo",
  subsets: ["latin"],
  weight: ["400", "500", "700"]
})
const ptSans = PT_Sans({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: ["700"]
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${ptSans.variable} ${arimo.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        {children}</body>
    </html>
  );
}
